services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: recipes_user
      POSTGRES_PASSWORD: recipes_pass
      POSTGRES_DB: recipes_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - recipes-net

volumes:
  db_data:

networks:
  recipes-net:
    driver: bridge
